services:
  demo-portal:
    container_name: demo-portal
    image: dsuprunov/demo-portal:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
