services:
  demo-website:
    container_name: demo-website
    image: dsuprunov/demo-website:1.0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
