apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | quote }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | quote }}
    spec:
{{- with .Values.podSecurityContext }}
      securityContext:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ .Values.name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
{{- with .Values.containerSecurityContext }}
          securityContext:
{{- toYaml . | nindent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
{{- with .Values.env }}
          env:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.resources }}
          resources:
{{- toYaml . | nindent 12 }}
{{- end }}
