name: demo-website

image:
  repository: dsuprunov/demo-website
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false

env:
  - name: PORT
    value: "3000"
